// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntmbomglzpmbpcczofmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50bWJvbWdsenBtYnBjY3pvZm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NzQyODAsImV4cCI6MjA2MzQ1MDI4MH0.iLboqK-z7WIVg_9Ag3i7NOi3zDxV1_xpCy8XPbDdf0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);